import Groq from 'groq-sdk';
import { GROQ_API_KEY } from '../config/config.js';

const groq = new Groq({ apiKey: GROQ_API_KEY });
// Groq model options
const GROQ_MODELS = {
    fast: 'llama-3.1-8b-instant', // Fastest, good for simple parsing
    balanced: 'llama-3.3-70b-versatile', // Best balance of speed/quality
    detailed: 'llama-3.3-70b-versatile', // Most detailed (using same as balanced)
  };

  export const AI_CONFIG = {
    maxTokens: 2000, // Maximum number of tokens in a response
    temperature: 0.7, // Creativity / randomness (0 = deterministic, 1 = very creative)
    timeout: 60000, // Timeout in milliseconds (e.g., 60 seconds)
  };
// Generate portfolio content using AI
export const generatePortfolioContent = async (prompt) => {
  try {
    console.log('🤖 Generating portfolio content with AI...');

    // Select a model
    const selectedModel = GROQ_MODELS.balanced; // or fast / detailed

    const systemPrompt = `You are a professional portfolio website content generator. Generate high-quality, engaging, and professional content for portfolio websites. 

IMPORTANT: Return ONLY valid JSON format without any markdown code blocks, backticks, or additional text. Do not wrap the JSON in \`\`\`json code blocks.

Be creative but professional, and tailor content to the specific role and experience level.`;

    const completion = await groq.chat.completions.create({
      model: selectedModel,
      max_tokens: AI_CONFIG.maxTokens,
      temperature: AI_CONFIG.temperature,
      messages: [
        {
          role: 'system',
          content: systemPrompt,
        },
        {
          role: 'user',
          content: `${prompt}

Return ONLY the JSON object with this exact structure (no code blocks, no backticks, no additional text):
{
  "hero": {
    "headline": "string",
    "subheading": "string", 
    "cta": "string"
  },
  "about": {
    "introduction": "string (2-3 sentences)",
    "highlights": ["string", "string", "string"]
  },
  "services": [
    {
      "title": "string",
      "description": "string",
      "icon": "string"
    }
  ],
  "contact": {
    "cta": "string",
    "description": "string"
  }
}`,
        },
      ],
      temperature: 0.1, // Low temperature for consistent JSON output
      max_tokens: 4000, // Adjust based on expected output size
      top_p: 0.9,
      stream: false,
    });

    const content = completion.choices[0]?.message?.content;

    if (!content) {
      throw new Error('No content generated by AI');
    }

    console.log('Raw AI response:', content); // Debug log

    // Clean the content by removing markdown code blocks and extra whitespace
    let cleanedContent = content.trim();

    // Remove markdown code blocks if present
    cleanedContent = cleanedContent.replace(/^```json\s*/, '');
    cleanedContent = cleanedContent.replace(/^```\s*/, '');
    cleanedContent = cleanedContent.replace(/\s*```$/, '');
    cleanedContent = cleanedContent.trim();

    // Parse and validate JSON response
    const parsedContent = JSON.parse(cleanedContent);

    // Validate structure
    validatePortfolioContent(parsedContent);

    console.log('✅ Portfolio content generated successfully');
    return parsedContent;
  } catch (error) {
    console.error('AI portfolio content generation failed:', error);

    // If JSON parsing fails, try to extract JSON from response
    if (error instanceof SyntaxError && error.message.includes('JSON')) {
      try {
        const content = completion.choices[0]?.message?.content; // Fixed: moved completion reference inside try block

        if (!content) {
          throw new Error('No content to extract JSON from');
        }

        // Try multiple extraction methods
        let extractedJson = null;

        // Method 1: Extract content between first { and last }
        const firstBrace = content.indexOf('{');
        const lastBrace = content.lastIndexOf('}');

        if (firstBrace !== -1 && lastBrace !== -1 && lastBrace > firstBrace) {
          const jsonString = content.substring(firstBrace, lastBrace + 1);
          extractedJson = JSON.parse(jsonString);
        } else {
          // Method 2: Try regex match
          const jsonMatch = content.match(/\{[\s\S]*\}/);
          if (jsonMatch) {
            extractedJson = JSON.parse(jsonMatch[0]);
          }
        }

        if (extractedJson) {
          validatePortfolioContent(extractedJson);
          console.log(
            '✅ Successfully extracted and validated JSON from AI response'
          );
          return extractedJson;
        }
      } catch (extractError) {
        console.error('Failed to extract JSON from AI response:', extractError);
      }
    }

    throw new Error(`AI content generation failed: ${error.message}`);
  }
};

// Enhance individual project using AI
export const enhanceProject = async (prompt) => {
  try {
    console.log('🚀 Enhancing project with AI...');

    const selectedModel = GROQ_MODELS.balanced;

    const systemPrompt = `You are a project enhancement specialist. Transform basic project information into compelling portfolio content. Focus on impact, technical achievements, and business value. Always return valid JSON format.`;

    const completion = await groq.chat.completions.create({
      model: selectedModel,
      max_tokens: 1000,
      temperature: 0.6,
      messages: [
        {
          role: 'system',
          content: systemPrompt,
        },
        {
          role: 'user',
          content: `${prompt}\n\nReturn JSON with this exact structure:
{
  "name": "string",
  "tagline": "string (compelling one-liner)",
  "description": "string (2-3 sentences)",
  "challenge": "string (what problem was solved)",
  "solution": "string (how it was solved)",
  "technologies": ["string", "string"],
  "features": ["string", "string", "string"],
  "metrics": ["string", "string"],
  "images": {
    "hero": "string (placeholder URL)",
    "gallery": ["string"]
  }
}`,
        },
      ],
    });

    const content = completion.choices[0]?.message?.content;

    if (!content) {
      throw new Error('No project enhancement generated by AI');
    }

    const parsedContent = JSON.parse(content);

    // Validate structure
    validateProjectContent(parsedContent);

    console.log('✅ Project enhanced successfully');
    return parsedContent;
  } catch (error) {
    console.error('AI project enhancement failed:', error);

    // Try to extract JSON if parsing fails
    if (error instanceof SyntaxError) {
      try {
        const content = completion?.choices[0]?.message?.content;
        const jsonMatch = content.match(/\{[\s\S]*\}/);
        if (jsonMatch) {
          const extractedJson = JSON.parse(jsonMatch[0]);
          validateProjectContent(extractedJson);
          return extractedJson;
        }
      } catch (extractError) {
        console.error('Failed to extract project JSON:', extractError);
      }
    }

    throw new Error(`AI project enhancement failed: ${error.message}`);
  }
};

// Generate multiple project enhancements in batch
export const enhanceProjectsBatch = async (projects, analysisContext) => {
  const enhancedProjects = [];
  const errors = [];

  // Process projects in batches to avoid rate limits
  const batchSize = 3;

  for (let i = 0; i < projects.length; i += batchSize) {
    const batch = projects.slice(i, i + batchSize);
    const batchPromises = batch.map(async (project, index) => {
      try {
        const prompt = createProjectEnhancementPrompt(project, analysisContext);
        return await enhanceProject(prompt);
      } catch (error) {
        console.error(`Failed to enhance project ${project.name}:`, error);
        errors.push({ project: project.name, error: error.message });
        return null;
      }
    });

    const batchResults = await Promise.all(batchPromises);
    enhancedProjects.push(...batchResults.filter(Boolean));

    // Add delay between batches to avoid rate limiting
    if (i + batchSize < projects.length) {
      await new Promise((resolve) => setTimeout(resolve, 1000));
    }
  }

  return {
    enhanced: enhancedProjects,
    errors: errors,
  };
};

// Generate professional summary for about section
export const generateProfessionalSummary = async (
  resumeData,
  analysisContext
) => {
  try {
    const prompt = `
Generate a professional summary for a ${analysisContext.roleType} with ${
      analysisContext.experienceLevel
    } experience.

Background:
- Name: ${resumeData.personalInfo?.name || 'Professional'}
- Experience: ${analysisContext.totalExperience} positions
- Projects: ${analysisContext.totalProjects} projects
- Key Skills: ${analysisContext.skills.slice(0, 5).join(', ')}
- Industries: ${analysisContext.industries.join(', ')}

Generate a compelling professional summary (2-3 sentences) that highlights expertise, experience, and value proposition.
Return only the summary text, no JSON or formatting.
`;

    const selectedModel = GROQ_MODELS.balanced; // or fast / detailed

    const completion = await groq.chat.completions.create({
      model: selectedModel,
      max_tokens: 200,
      temperature: 0.7,
      messages: [
        {
          role: 'user',
          content: prompt,
        },
      ],
    });

    const summary = completion.choices[0]?.message?.content?.trim();

    if (!summary) {
      throw new Error('No summary generated');
    }

    return summary;
  } catch (error) {
    console.error('Failed to generate professional summary:', error);
    throw error;
  }
};

// Generate SEO-friendly meta content
export const generateSEOContent = async (portfolioData) => {
  try {
    const prompt = `
Generate SEO-optimized meta content for a portfolio website.

Portfolio Info:
- Name: ${portfolioData.personalInfo?.name || 'Professional'}
- Role: ${portfolioData.roleType}
- Key Skills: ${portfolioData.skills?.join(', ') || 'Various skills'}
- Industry Focus: ${
      portfolioData.industries?.join(', ') || 'Multiple industries'
    }

Generate:
1. Meta title (50-60 characters)
2. Meta description (150-160 characters)
3. 5-7 relevant keywords

Return as JSON:
{
  "title": "string",
  "description": "string",
  "keywords": ["string", "string", "string"]
}
`;

const selectedModel = GROQ_MODELS.balanced;

    const completion = await groq.chat.completions.create({
      model: selectedModel,
      max_tokens: 300,
      temperature: 0.5,
      messages: [
        {
          role: 'user',
          content: prompt,
        },
      ],
    });

    const content = completion.choices[0]?.message?.content;
    return JSON.parse(content);
  } catch (error) {
    console.error('Failed to generate SEO content:', error);
    throw error;
  }
};

// Validation functions
const validatePortfolioContent = (content) => {
  const required = ['hero', 'about', 'services', 'contact'];

  for (const section of required) {
    if (!content[section]) {
      throw new Error(`Missing required section: ${section}`);
    }
  }

  // Validate hero section
  if (!content.hero.headline || !content.hero.subheading || !content.hero.cta) {
    throw new Error('Hero section missing required fields');
  }

  // Validate about section
  if (!content.about.introduction || !Array.isArray(content.about.highlights)) {
    throw new Error('About section missing required fields');
  }

  // Validate services
  if (!Array.isArray(content.services) || content.services.length === 0) {
    throw new Error('Services section must be a non-empty array');
  }

  content.services.forEach((service, index) => {
    if (!service.title || !service.description || !service.icon) {
      throw new Error(`Service ${index} missing required fields`);
    }
  });

  // Validate contact
  if (!content.contact.cta || !content.contact.description) {
    throw new Error('Contact section missing required fields');
  }
};

const validateProjectContent = (project) => {
  const required = ['name', 'tagline', 'description', 'challenge', 'solution'];

  for (const field of required) {
    if (!project[field]) {
      throw new Error(`Project missing required field: ${field}`);
    }
  }

  if (!Array.isArray(project.technologies)) {
    throw new Error('Technologies must be an array');
  }

  if (!Array.isArray(project.features)) {
    throw new Error('Features must be an array');
  }

  if (!Array.isArray(project.metrics)) {
    throw new Error('Metrics must be an array');
  }
};

// Helper function to create project enhancement prompt
const createProjectEnhancementPrompt = (project, analysisContext) => {
  return `
Enhance this ${analysisContext.roleType} project for a portfolio:

Project Details:
- Name: ${project.name || 'Unnamed Project'}
- Description: ${project.description || 'No description available'}
- Technologies: ${(project.technologies || []).join(', ') || 'Not specified'}
- URL: ${project.url || 'Not available'}
- GitHub: ${project.github || 'Not available'}

Context:
- Professional Level: ${analysisContext.experienceLevel}
- Industry: ${analysisContext.industries?.join(', ') || 'General'}
- Role Focus: ${analysisContext.roleType}

Make the project sound impressive and results-focused. Include specific technical achievements and business impact where possible.
`;
};

// Rate limiting and retry logic
const withRetry = async (fn, maxRetries = 3, baseDelay = 1000) => {
  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    try {
      return await fn();
    } catch (error) {
      if (attempt === maxRetries) {
        throw error;
      }

      // Check if it's a rate limit error
      if (error.status === 429 || error.code === 'rate_limit_exceeded') {
        const delay = baseDelay * Math.pow(2, attempt - 1); // Exponential backoff
        console.warn(
          `Rate limited, retrying in ${delay}ms (attempt ${attempt}/${maxRetries})`
        );
        await new Promise((resolve) => setTimeout(resolve, delay));
      } else {
        throw error; // Don't retry non-rate-limit errors
      }
    }
  }
};

// Export service with retry wrapper
export const aiService = {
  generatePortfolioContent: (prompt) =>
    withRetry(() => generatePortfolioContent(prompt)),
  enhanceProject: (prompt) => withRetry(() => enhanceProject(prompt)),
  enhanceProjectsBatch,
  generateProfessionalSummary: (resumeData, context) =>
    withRetry(() => generateProfessionalSummary(resumeData, context)),
  generateSEOContent: (portfolioData) =>
    withRetry(() => generateSEOContent(portfolioData)),
};
